### ISSUE TITLE
base upper bound too low

### ISSUE THREAD

**Issue by ocharles** [tel/hexpat-lens#11]

**Comment by tel** [comment]
Bumped! Thanks :)

**Comment by tel** [comment]
If you're actively using this package and want a commit bit, please let me know. I'd be happy to give you one.

**Comment by ocharles** [comment]
Feel free to chuck one my way. We're using it but I don't see us needing to do any more XML parsing, but can't hurt to have two people!

**Comment by tel** [comment]
:+1:

**Comment by tel** [comment]
Spent way too long trying to invite `cocharles`.... but should be coming your way now :)

**Comment by tel** [comment]
Also, what's your Hackage user? I'll add you there as well

**Comment by tel** [comment]
Nm, found it

**Comment by ocharles** [comment]
Thanks!
