### ISSUE TITLE
Upper bounds for lens dependency

### ISSUE THREAD

**Issue by andrewthad** [tel/hexpat-lens#4]
hexpat-lens is a super helpful package for me. Can you bump the lens dependency upper bound to `lens < 5.0` so that this can build with the `lens` on the latest stackage LTS snapshot? (I'm running it with lens 4.6.0.1 right now, so I know that works, but I'm pretty sure that lens hasn't made any breaking changes since then).

**Comment by tel** [comment]
Similar to #5 I'm happy to do this but won't have time for a little bit. If it's time sensitive feel free to leave a PR and I can merge to master online.

It'll probably still be a few days before I can bump the version and upload to Hackage, though.
