### ISSUE TITLE
Fixity for `./`

### ISSUE THREAD

**Issue by andrewthad** [tel/hexpat-lens#5]
Could you add this line

    infixr 9 ./

to the Generic and Unqualified modules? That will let people write things like this:

    xml ^.. _XML ./ named "Report" ./ named "ReportHost" ./ named "ReportItem" . attributes

Right now, the above line won't work because operators without fixity declarations (like `./`) default to `infixl 9` and consequently cannot be used with `.` which is `infixr 9`.

**Comment by tel** [comment]
I definitely approve this change! I'd be happy to accept a PR, or I can get to this in a a few days.

**Comment by andrewthad** [comment]
I'll put up a PR changing this and the lens dependency.
